services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres_zz
    environment:
      - 'POSTGRES_DB=filmediamante'
      - 'POSTGRES_PASSWORD=filmediamante'
      - 'POSTGRES_USER=filmediamante'
    ports:
      - '5432:5432'