CREATE TABLE filmes
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo         VARCHAR(150),
    genero         VARCHAR(100),
    ano_lancamento INTEGER                                 NOT NULL,
    diretor        VARCHAR(120),
    capa_url       VARCHAR(500),
    data_cadastro  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_filmes PRIMARY KEY (id)
);